### ISSUE TITLE
UI and Channel type

### ISSUE THREAD

**Issue by jupiter1390** [LazoYoung/Radio4U#6]
1. ~~Action Message or Chat message informing the song currently played when connected to radio/playlist~~ Moved to #5
2. ~~Coordinate based radio, with controllable volume value(no limit?)~~ Moved to #4

**Comment by LazoYoung** [comment]
@jupiter1390 1st request was merged into #5 
If you'd like to receive notification of the progress, click **watch** on top of this page.
